server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-auth
              uri: ${MS_AUTH_URL:http://localhost:8091}
              predicates:
                - Path=/api/auth/**

            - id: ms-eventos
              uri: ${MS_EVENTOS_URL:http://localhost:8081}
              predicates:
                - Path=/api/eventos/**

            - id: ms-recintos
              uri: ${MS_RECINTOS_URL:http://localhost:8082}
              predicates:
                - Path=/api/recintos/**

            - id: ms-tickets
              uri: ${MS_TICKETS_URL:http://localhost:8083}
              predicates:
                - Path=/api/tickets/**

            - id: ms-ventas
              uri: ${MS_VENTAS_URL:http://localhost:8084}
              predicates:
                - Path=/api/ventas/**

            - id: ms-validacion
              uri: ${MS_VALIDACION_URL:http://localhost:8085}
              predicates:
                - Path=/api/validacion/**

            - id: ms-artistas
              uri: ${MS_ARTISTAS_URL:http://localhost:8086}
              predicates:
                - Path=/api/artistas/**

            - id: ms-preventa
              uri: ${MS_PREVENTA_URL:http://localhost:8087}
              predicates:
                - Path=/api/preventa/**

            - id: ms-devoluciones
              uri: ${MS_DEVOLUCIONES_URL:http://localhost:8088}
              predicates:
                - Path=/api/devoluciones/**

            - id: ms-promotores
              uri: ${MS_PROMOTORES_URL:http://localhost:8089}
              predicates:
                - Path=/api/promotores/**

            - id: ms-streaming
              uri: ${MS_STREAMING_URL:http://localhost:8090}
              predicates:
                - Path=/api/streamings/**
